# Generated by Django 3.2.16 on 2023-01-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'core_categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'core_familia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=300)),
                ('precio', models.IntegerField()),
                ('vencimiento', models.DateField()),
                ('stock', models.IntegerField()),
                ('stock_critico', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('oferta', models.BooleanField(default='0')),
            ],
            options={
                'db_table': 'core_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('nombre', models.TextField()),
                ('telefono', models.IntegerField()),
                ('rubro', models.TextField()),
            ],
            options={
                'db_table': 'core_proveedor',
                'managed': False,
            },
        ),
    ]
